### ISSUE TITLE
Build Failing on Sample Report

### ISSUE THREAD

**Issue by melanieseifert** [infusionsoft/sleuth-sketch-figma#16]
I am trying to run build off of the sample report and I am getting the following error.  (Disclaimer:  I'm a total npm noob so if you can help with specific commands that would be great.  TIA)

 ERROR  Failed to compile with 2 errors                              10:31:45 AM

 error  in ./src/App.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):

Vue packages version mismatch:

- vue@2.6.11 (/Users/melanie/Applications/sleuth-sketch-figma-master/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.12 (/Users/melanie/Applications/sleuth-sketch-figma-master/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./src/main.js 8:0-24 19:13-16
 @ multi ./src/main.js

 error  in ./src/App.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Users/melanie/Applications/sleuth-sketch-figma-master/node_modules/@vue/component-compiler-utils/dist/parse.js:15:23)
    at Object.module.exports (/Users/melanie/Applications/sleuth-sketch-figma-master/node_modules/vue-loader/lib/index.js:67:22)

 @ ./src/main.js 8:0-24 19:13-16
 @ multi ./src/main.js

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sleuth-sketch@1.2.3 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleuth-sketch@1.2.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/melanie/.npm/_logs/2021-02-25T16_31_45_782Z-debug.log
Melanies-MacBook-Pro-2:sleuth-sketch-figma-master melanie$

**Comment by MihaelN** [comment]
Facing the exact same issue, any ideas how to get past this?

**Comment by MihaelN** [comment]
I figured out what the issue was. `Vue` and `Vue-template-compiler` versions are not matching. I have changed both dependency versions to `2.6.11` and have run `npm i` and it seems to be fixed.

Hope this helps.
